spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_railway_booking_project
    username: postgres
    password: Jayxunbey2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      expiration-time-minute: 10
      expiration-time-minute-with-remember: 60
      secret-key: KAjfenIF445FDafe353855-fd43lmgKFD9dkv

    code:
      sign:
        up:
          expire-minute: 3
          length: 4

  mail:
    host: smtp.gmail.com
    port: 465
    username: muxammedovjayxun@gmail.com
    password: glhgmbuolybjegno
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
          ssl:
            enable: true