spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_railway_booking_project
    username: postgres
    password: Jayxunbey2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      expiration-time-minute: 10
      expiration-time-minute-with-remember: 60
      secret-key: KAjfenIF445FDafe353855-fd43lmgKFD9dkv

